import {
  Axios,
  Bootstrap,
  CSS,
  Docker,
  Figma,
  Firebase,
  Formik,
  Git,
  Github,
  HTML,
  JavaScript,
  MaterialUI,
  Mobx,
  NextJS,
  ReactHookForm,
  ReactJS,
  ReactRouterDom,
  Redux,
  Responsive,
  RestApi,
  StoryBook,
  StyledComponents,
  Tailwind,
  TypeScript,
  Vercel,
  Webpack
} from '@/assets';
import { IMySkillsData } from '@/types/my-skills';

const MY_SKILLS_DATA: IMySkillsData[] = [
  { id: 1, title: 'HTML', ICON: HTML },
  { id: 2, title: 'CSS', ICON: CSS },
  { id: 3, title: 'JavaScript', ICON: JavaScript },
  { id: 4, title: 'Typescript', ICON: TypeScript },
  { id: 5, title: 'ReactJS', ICON: ReactJS },
  { id: 6, title: 'NextJS', ICON: NextJS },
  { id: 7, title: 'Redux', ICON: Redux },
  { id: 8, title: 'Redux toolkit', ICON: Redux },
  { id: 9, title: 'RTK Query', ICON: Redux },
  { id: 10, title: 'REST API', ICON: RestApi },
  { id: 11, title: 'Git', ICON: Git },
  { id: 12, title: 'Github', ICON: Github },
  { id: 13, title: 'Vercel', ICON: Vercel },
  { id: 14, title: 'Figma', ICON: Figma },
  { id: 15, title: 'Adaptive Design', ICON: Responsive },
  { id: 16, title: 'Webpack', ICON: Webpack },
  { id: 17, title: 'Storybook', ICON: StoryBook },
  { id: 18, title: 'Mobx', ICON: Mobx },
  { id: 19, title: 'React Hook Horm', ICON: ReactHookForm },
  { id: 20, title: 'Formik', ICON: Formik },
  { id: 22, title: 'Styled Components', ICON: StyledComponents },
  { id: 23, title: 'Docker', ICON: Docker },
  { id: 24, title: 'Firebase', ICON: Firebase },
  { id: 25, title: 'React Router dom v6.10', ICON: ReactRouterDom },
  { id: 26, title: 'Material UI', ICON: MaterialUI },
  { id: 27, title: 'Axios', ICON: Axios },
  { id: 28, title: 'Tailwind CSS', ICON: Tailwind },
  { id: 29, title: 'Bootstrap', ICON: Bootstrap }
];

export default MY_SKILLS_DATA;
